server:
  port: 8081
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suzhenglong/spring-cloud-config-repo      # 配置Git仓库的地址
          username: zhenglongsu@163.com                                         # Git仓库的账号
          password: NieLong504473410                                            # Git仓库的密码


# 测试：
# 1.观察启动日志
# 2.访问 http://localhost:8081/microservice-foo/dev
# 3 http://localhost:8081/foo-config-2.0/microservice-foo-dev.yml