server:
  port: 8070
spring:
  application:
    name: microservice-sidecar-node-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
sidecar:
  port: 8060                                      # Node.js微服务的端口
  health-uri: http://localhost:8060/health.json   # Node.js微服务的健康检查URL

  #测试
  # microservice-discovery-eureka
  # microservice-provider-user
  # node-service node node-service.js
  # 非JVM微服务访问JVM微服务
  # http://localhost:8070/microservice-provider-user/22