server:
  port: 9411
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.121.181:5673
      password: guest
      username: guest
      queue: zipkin
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://192.168.121.181:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1

# microservice-trace-zipkin-server-stream-elasticsearch
# microservice-simple-provider-user-sleuth-zipkin-stream
# microservice-simple-consumer-movie-sleuth-zipkin-stream
# http://localhost:8501/user/11
# http://192.168.121.181:9200/_search