server:
  port: 8501

spring:
  application:
    name: microservice-simple-consumer-movie-sleuth-zipkin-stream
  rabbitmq:
    host: 192.168.121.181
    port: 5673
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
    build:
      artifactId: @project.artifactId@
      version: @project.version@

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG

#测试
#启动  microservice-simple-provider-user-sleuth-zipkin-stream
# http://localhost:8501/user/11
# http://localhost:9411
