server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul-fallback
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true