server:
  port: 8084
spring:
  application:
    name: microservice-config-server-health
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suzhenglong/spring-cloud-config-repo      # 配置Git仓库的地址
          username: zhenglongsu@163.com                                         # Git仓库的账号
          password: NieLong504473410                                            # Git仓库的密码
        health:
          repositories:
            a-foo: 
              label: foo-config-2.0
              name: microservice-foo
              profiles: dev
management:
  security:
    enabled: false
# http://localhost:8084/health