server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: microservice-consumer-movie-feign-multiple-params
    prefer-ip-address: true     #访问路径可以显示IP地址

spring:
  application:
    name: microservice-consumer-movie-feign-multiple-params

logging:
  level:
    #将fegin的日志设置为debug 因为fegin的Logger.Level只对Debug做出响应
    com.suzl.cloud.study.feign.UserFeignClient: DEBUG
feign:
  client:
    config:
      MICROSERVICE-PROVIDER-USER-MULTIPLE-PARAMS:
        loggerLevel: full


info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
    build:
      artifactId: @project.artifactId@
      version: @project.version@


# microservice-discovery-eureka
# microservice-provider-user-multiple-params
# http://localhost:8010/user/11
# http://localhost:8010/user/get0?id=11&username=张三
# http://localhost:8010/user/get1?id=11&username=张三
# http://localhost:8010/user/get2?id=11&username=张三
# http://localhost:8010/user/post?id=11&username=张三