server:
  port: 8071
spring:
  application:
    name: microservice-sidecar-client-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true

  #测试
  # microservice-discovery-eureka
  # node-service node node-service.js
  # microservice-sidecar-node-service
  # JVM微服务访问非JVM微服务
  # http://localhost:8071/test
  # http://localhost:7001/eureka/apps/microservice-sidecar-node-service