server:
  port: 8081
spring:
  application:
    name: microservice-config-server-authenticating
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suzhenglong/spring-cloud-config-repo      # 配置Git仓库的地址
          username: zhenglongsu@163.com                                         # Git仓库的账号
          password: NieLong504473410                                            # Git仓库的密码

security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: user                  # 配置登录的账号是user
    password: 123456            # 配置登录的密码是password123

# http://localhost:8081/microservice-foo/dev