server:
  port: 8508

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: microservice-consumer-movie-feign
    prefer-ip-address: true     #访问路径可以显示IP地址

spring:
  application:
    name: microservice-consumer-movie-feign

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
    build:
      artifactId: @project.artifactId@
      version: @project.version@
